Added report for All the capital cities in the world organized by largest population to smallest.
sousajf1/sem pull request #53
Opened 2021-04-10 15:13 UTC by Lindon-Jackasal

Team,

This pull request contains the following:
-The report for all the capital cities in the world organised by largest population to smallest.
-Updated README.md file with the Project Requirements Met table to show all the requirements we need to meet or requirements we have already met. Please feel free to update the table as we progress.
-Added new java classes: CapitalCities.java, CapitalCitiesDAO interface, CapitalCitiesDAOImpl.java, CapitalCitiesReport.java & ReportCapitalCities.java

Kindly review and provide your feedback. If all is well, kindly approve and merge this PR.

2021-04-11 10:10 UTC, sousajf1 requested changes
looks good overall, few remarks, please take a look at those

2021-04-11 10:10 UTC, sousajo-cc commented on README.md
>  - [![Releases](https://img.shields.io/github/release/sousajf1/sem/all.svg?style=flat-square)](https://github.com/sousajf1/sem/releases)
looks good the table ty. Can you please also add the screenshot for the other already adressed cases?

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/App.java
> +import java.sql.SQLException;
is this import needed here?

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/App.java
> +
sorry for being picky but avoid this pointless new lines, maybe it's your editor, it just adds noise to the review. here it's fine but in a big project if your editor does this all the time, people will just ask for changes in your PR right away to fix the newline mess without even taking a look at the logic of your changes :)

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/CapitalCitiesDAO.java
> +    List<CapitalCities> getAllCapitalCities();
By the javadocs comment it seems that a more appropriate name would be `getAllCapitalCitiesPopFromLargestToSmallest`

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/App.java
> +        for (reportTypes t : reportTypes.values()) {
please fix your editor, this is just whitespace noise :)

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/CapitalCitiesReport.java
> +        capitalCitiesWorld();
keeping the same naming convention as the other report should be fine here, so the method name can be `largestToSmallest`

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/CapitalCitiesReport.java
> +        capitalCitiesWorld();
and maybe the `interface Report` could be reused

2021-04-11 10:10 UTC, sousajf1 commented on src/main/java/com/napier/sem/ReportCapitalCities.java
> +}
can `interface Report `be re-used?

2021-04-11 13:38 UTC, sousajf1 commented
please just do reset your local branch to `3cc2c1e296f20ac7936737b30deccdd959284b55`.
Everything there was fine except for the whitespaces and the `ReportCapitalCities` newly interface.
Just reset your branch to it and then reuse the `Report` interface instead of `ReportCapitalCities` that you created.

This newly changes are not good I'm sorry.

2021-04-11 13:40 UTC, Lindon-Jackasal commented
The changes are okay... I will explain

2021-04-11 15:11 UTC, Lindon-Jackasal commented
Hey Jorge,

I made some changes. Please review.

2021-04-11 19:36 UTC, sousajf1 approved these changes, later dismissed

2021-04-11 19:36 UTC, sousajo-cc commented on src/main/java/com/napier/sem/ReportTypes.java
> +
please don't add this white spaces. This makes the coded hard to read, and it's not consistent

2021-04-11 19:36 UTC, sousajo-cc commented on src/main/java/com/napier/sem/ReportTypes.java
> +public class ReportTypes implements Report {
why this? You can have a` countryReport` class and a `CapitalCitiesReport` both implementing the same interface.

2021-04-12 06:19 UTC, sousajf1 approved these changes
looks way better, thanks :D

2021-04-12 06:20 UTC, merged